name: keyboard cron
on:
  schedule:
    - cron: "30 10-23/2 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@main
        with:
          node-version: 16.x
      - name: intall packages
        run: |
          yarn --frozen-lockfile
      - name: run action script
        run: |
          yarn action
        env:
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          CHANNEL_ID: ${{secrets.CHANNEL_ID}}
          FB_PROJECT_ID: ${{secrets.FB_PROJECT_ID}}
          FB_PRIVATE_KEY: ${{secrets.FB_PRIVATE_KEY}}
          FB_CLIENT_EMAIL: ${{secrets.FB_CLIENT_EMAIL}}
