name: on push flow
on:
  push:
    branches:
      - "main"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: intall packages
        run: |
          yarn --frozen-lockfile
      - name: run action script
        run: |
          yarn action
